---
- hosts: all

  tasks:
  - name: Copy the urlshort repo
    git:
      repo=git://github.com/srsakhamuri/urlshort
      dest="{{ ansible_env.HOME }}/urlshort"


  - name: install make
    become: yes
    raw: (apt -y update && apt install -y make python-pip && pip install virtualenv)

  - name: setup env
    command: make env
    args:
      chdir: "{{ ansible_env.HOME }}/urlshort"

  - name: Start application
    shell: "start-stop-daemon --start --quiet -m --pidfile {{ ansible_env.HOME }}/urlshort.pid --background --exec {{ ansible_env.HOME }}/urlshort/.env/bin/python {{ ansible_env.HOME }}/urlshort/manage.py runserver"
    args:
      executable: "/bin/bash"
